### ISSUE TITLE
Example for Subcollection

### ISSUE THREAD

**Issue by agilecrm** [wovalle/fireorm#12]
Hi,

First of all thank you soo much for this framework and the documentation is really good as well.
But one example I am unable to find is inserting a 'Subcollection'.

Can you please provide one?

Thank you

**Comment by wovalle** [comment]
Hey! Thanks for reaching out.

Yes, documentation for SubCollections can be better. Will leave issue open until improved.

In the meantime you can see examples for SubCollections in the unit tests. After retrieving the initial collection (i.e. using findById), each field declared as a model SubCollection, will contain a repository for the SubCollection

https://github.com/wovalle/fireorm/blob/62a4708a36110541fa1aa804645f6322de3d64c1/src/BaseFirestoreRepository.spec.ts#L174-L194

Please be aware that right now there is an issue [if you try to retrieve a collection that doesn't have any fields, just subcollections](https://github.com/wovalle/fireorm/issues/10)

**Comment by wovalle** [comment]
Hey @agilecrm ! You can now find examples with SubCollections in this file:

https://github.com/wovalle/fireorm/tree/master/examples/3-subcollections
