### ISSUE TITLE
Subcollections are wiped from entity when updating

### ISSUE THREAD

**Issue by joemckie** [wovalle/fireorm#121]
When updating an entity, any subcollections are deleted from the object.

Example with `pictures` as a subcollection

```ts
const user = /* get user */

console.log(user.pictures); // this is a valid subcollection here

user.name = 'New name';

await update(user);

console.log(user.pictures); // undefined
```

The user returned by the `update` method is missing subcollections, and the original reference to `user` has its subcollections deleted

**Comment by zhirschtritt** [comment]
I think this one is pretty straight forward, @wovalle thoughts? https://github.com/wovalle/fireorm/pull/122

**Comment by wovalle** [comment]
You're totally right @joemckie and yes @zhirschtritt, this should be straight forward, I'll check your PR!
