### ISSUE TITLE
Passing information out of transactions

### ISSUE THREAD

**Issue by joantune** [wovalle/fireorm#127]
Hi!

First of all - I have relatively low hands on experience with Typescript - so take that into context on my question.

Shouldn't the runTransaction return a `Promise<any>` to get the use case demonstrated by: https://firebase.google.com/docs/firestore/manage-data/transactions#passing_information_out_of_transactions

possible?

How do we take data away from transactions ??

This could be very useful to do a 'getOrCreate' kind of method - which is a typical requirement for a concurrent application

**Comment by joantune** [comment]
I'm guessing I can make an 'external' Promise that will be resolved by the transaction ?!

and then eventually await on it?!

does that make sense?

**Comment by wovalle** [comment]
That's a good point 🤔.

I'll check this out as soon as I finish #115

**Comment by wovalle** [comment]
Hey @joantune, found a way to return info from transactions in a type-safe way! See https://fireorm.js.org/#/Transactions?id=returning-values-from-transactions
