### ISSUE TITLE
Returning values from Transactions

### ISSUE THREAD

**Issue by joantune** [wovalle/fireorm#129]
Shan't this line https://github.com/wovalle/fireorm/blob/2e45f10a7973f6113463ee65602fc9b3e67832a3/src/BaseFirestoreRepository.ts#L95

be `Promise<any>` ? so that the following use case applies: https://firebase.google.com/docs/firestore/manage-data/transactions#passing_information_out_of_transactions
?

**Comment by joantune** [comment]
PS: I'm trying to do that change and I'll try it out - if it works I'll let you know/do PR

**Comment by wovalle** [comment]
It does return a promise, but a void one. If you modify the code to return
the promise returned by the transaction it *should* work (not really sure).

**Comment by wovalle** [comment]
Hey, this was closed in #115. See https://fireorm.js.org/#/Transactions?id=returning-values-from-transactions
