### ISSUE TITLE
findById in #create method in Transactions limits applicability 

### ISSUE THREAD

**Issue by joantune** [wovalle/fireorm#130]
https://github.com/wovalle/fireorm/blob/2e45f10a7973f6113463ee65602fc9b3e67832a3/src/BaseFirestoreTransactionRepository.ts#L53

The line above really constrains the usage of a transaction - as all reads need to be done before the writes (see https://firebase.google.com/docs/firestore/manage-data/transactions#transactions)   - 

```
Read operations must come before write operations.
```

apologies for having just filling issues but I haven't had time to contribute - I think this time I'll do so - anyway - I'm putting here the issues that I find at least so that me or someone else can reference them in PRs

I'm tempted to edit the code and simply don't do the check and let it fail in case it already exists

I'll provide a PR

**Comment by wovalle** [comment]
Totally agree with this! Make a PR removing it and I'll merge it :)

**Comment by wovalle** [comment]
Hey @joantune, this was done in the last release :) 

Please update to v0.13.1.
