### ISSUE TITLE
Transactions - better implementation

### ISSUE THREAD

**Issue by joantune** [wovalle/fireorm#131]
A transaction in Firestore is orthogonal to the object being updated

as is implemented right now - it only allows you to update within a transaction objects from that collection/sub-collection

one way to allow this would be that all of the methods of `BaseFirestoreTransactionRepository` would allow a `BaseFirestoreRepository` as an argument with a readable `firestoreColRef` as to replace `this.collection` invocations by the foreigh repo's `firestoreColRef`

I'm really thinking of implementing this anyway

there might be a better way to do this though

**Comment by joantune** [comment]
@wovalle - added an example - at some level is messy - and it doesn't solve the `find` - are the finds even supposed to work with the transaciton?! anyway i'm using this at the moment and I have added this code so that you or someone - or even me (although RN constricted on time) can help

**Comment by joantune** [comment]
@wovalle (nevermind - it doesn't solve much of what I wanted 😅 - I'll come up with a better solution :) )

**Comment by wovalle** [comment]
Hey! yes I found that problem and started working in https://github.com/wovalle/fireorm/pull/115

Due to personal issues it's been pending for a long time. Tried to retake that PR last week but remember all the context needed to continue. I'll see your commits to compare the strategy you took

**Comment by wovalle** [comment]
Hey @joantune, finally I had time to finish this feature.

Documentation: https://fireorm.js.org/#/Transactions?id=transactions-in-multiple-repositories
