### ISSUE TITLE
Comparison with typesaurus

### ISSUE THREAD

**Issue by manwithsteelnerves** [wovalle/fireorm#134]
[Typesaurus](https://github.com/kossnocorp/typesaurus) seems to be another project solving similar problem as fireorm but I loved the approach of fireorm as its more expressive and readable.

But before picking up fireorm, it would be great if someone can list out the major problems you see with this package. And would be great to see a roadmap if any. I would be happy to contribute down the line.

As of now I see not supporting nested subcollections seems to be a major issue but I think some work is going on it.

**Comment by wovalle** [comment]
I wasn't aware of Typesaurus but it seems like a nice project! 

One major difference is that they wrap the firebase sdk to add more type-safety and handy helpers to firestore, this project is more geared to provide another way to interact with your firestore backend (using Repositories).

Is a cool project nevertheless and I might borrow some ideas :)
