### ISSUE TITLE
'typeof Todo' is not assignable to parameter of type 'Instantiable<IEntity>'.

### ISSUE THREAD

**Issue by NicholasLYang** [wovalle/fireorm#143]
Hi,

I'm trying to use fireorm, but I'm running into some confusing issues. I'm copying from the tutorial:
```
@Collection()
class Todo {
  id: string;
  text: string;
  done: Boolean;
}

export const testFireOrm = functions.https.onCall(async(data) => {
  const todoRepository = getRepository(Todo, firestore);
  const todo = new Todo();
  todo.text = "Check fireorm's Github Repository";
  todo.done = false;
  const todoDocument = await todoRepository.create(todo); // Create todo
  const mySuperTodoDocument = await todoRepository.findById(todoDocument.id); // Read todo
  console.log(mySuperTodoDocument);
})
```

Right now I get the following error:

```
Argument of type 'typeof Todo' is not assignable to parameter of type 'Instantiable<Todo>'.
```
Along with some errors about fields not being instantiated (I have strictNullChecks on). If I turn off strictNullChecks, all of the aforementioned errors go away and I get the following error:

```
Argument of type 'Firestore' is not assignable to parameter of type 'string'.
```

I'm not really sure what I'm doing wrong—I'm copying almost directly from the tutorial.

Just out of curiosity, is the library designed to work with strictNullChecks or the other strict options? I noticed they aren't turned on in the tsconfig for the repo.

Thanks,
Nicholas

**Comment by wovalle** [comment]
Hey!

Do you have a simple repo that I can use to reproduce the error?

**Comment by NicholasLYang** [comment]
Sure thing. Here's the [repo](https://github.com/NicholasLYang/fireorm-repro). Run `npm run tsc` to typecheck.

**Comment by wovalle** [comment]
Oh, I found the error. [Here](https://github.com/NicholasLYang/fireorm-repro/blob/master/index.ts#L20) you don't have to pass firestore as the second parameter. Check [this test](https://github.com/wovalle/fireorm/blob/master/test/functional/1-simple_repository.spec.ts#L12).

Just saw that is outdated in the README. Will fix it.

You can see the documentation in https://fireorm.js.org

**Comment by NicholasLYang** [comment]
Hmm okay so that solved one issue, thanks @wovalle. However when I turn strictNullChecks on I still get the following:

```
Argument of type 'typeof Todo' is not assignable to parameter of type 'Instantiable<IEntity>'.
```

Any idea why strictNullChecks is causing this problem?

Thanks again

**Comment by wovalle** [comment]
I cannot reproduce this. I managed to build successfully with this config. 

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "strict": true,
    "strictNullChecks": true,
    "experimentalDecorators": true,
    "target": "es2017"
  },
  "files": ["index.ts"]
}
```

```typescript
import * as admin from 'firebase-admin';
import { Collection, getRepository } from 'fireorm';

admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  databaseURL: process.env.FIREBASE_URL,
});
const firestore = admin.firestore();
firestore.settings({
  timestampsInSnapshots: true,
});

@Collection()
class Todo {
  constructor() {
    this.id = '';
    this.text = '';
    this.done = false;
  }

  id: string;
  text: string;
  done: Boolean;
}

const todoRepository = getRepository(Todo);

async function createTodo() {
  const todo = new Todo();
  todo.text = "Check fireorm's Github Repository";
  todo.done = false;

  const todoDocument = await todoRepository.create(todo); // Create todo
  const mySuperTodoDocument = await todoRepository.findById(todoDocument.id); // Read todo
  await todoRepository.update(mySuperTodoDocument); // Update todo
  await todoRepository.delete(mySuperTodoDocument.id); // Delete todo
}

createTodo();

```

**Comment by NicholasLYang** [comment]
Ah I figured out the issue. TypeScript doesn't like that I created a constructor that takes in arguments:
```
@Collection()
class Todo {
    id: string;
    text: string;
    done: Boolean;

    constructor(id: string, text: string, done: Boolean) {
        this.id = id;
        this.text = text;
        this.done = done;
    }
}
```

That's not great since I'm not a huge fan of initializing objects with dummy values. Ah well.

Thanks again for your help!

**Comment by wovalle** [comment]
Oh, yes, I forgot about this. Fireorm requires at least one parameter-less constructor to work (since it wouldn't know how to instantiate your class if it didn't have one). We had a great discussion about this in this issue: https://github.com/wovalle/fireorm/issues/117. Unfortunately I don't know how to enhance this.
