### ISSUE TITLE
Support for strictPropertyInitialization: true

### ISSUE THREAD

**Issue by taylorhoward92** [wovalle/fireorm#144]
I've had to set `"strictPropertyInitialization": false` to reliably use fireorm. I can get around it by using the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) on my class properties or making them all optional but that is really just a bit of a hack.

Unless I'm thinking about this the wrong way, to be able to avoid TypeScript property initialization errors I need constructors in my classes. I haven't figured out the internals of fireorm, but from my point-of-view as a user of fireorm, the issue is that a class with a constructor can't be used with the `@Subcollection` decorator. With the constructor in the subcollection class (see below) I get `Argument of type 'typeof Products' is not assignable to parameter of type 'Instantiable '` on the subcollection decorator.

Are there any plans to support this? How much work would it be?

**What I want to do**
```js
import { Collection, ISubCollection, SubCollection } from 'fireorm';

export class Products {
  constructor(category: string, price: number) {
    this.category = category;
    this.price = price;
  }
  
  id: string;
  category: string;
  price: number;
}

@Collection()
export default class ShoppingCart {
  constructor(user: string) {
    this.user = user;
  }
  
  id: string;
  user: string;

  @SubCollection(Products)
  marketplaceEntities: ISubCollection<Products>
}
```

**Comment by wovalle** [comment]
Hey, this limitation is being discussed in #117 (and recently in #143 but I prefer having only one ticket). At this moment I don't have a plan of how fireorm could work with constructor with parameters. If you have any ideas chime in in #117!
