### ISSUE TITLE
How can I use it in Plain Nodejs

### ISSUE THREAD

**Issue by AxeemHaider** [wovalle/fireorm#152]
I'm doing like this, but it a lot of syntax error.

```nodejs
const { Collection, getRepository } = require('fireorm');

@Collection()
class Todo {
  id: string;
  text: string;
  done: Boolean;
}

const todoRepository = getRepository(Todo);

const todo = new Todo();
todo.text = "Check fireorm's Github Repository";
todo.done = false;
```

Can you please provide any example how to use it in nodejs.

**Comment by wovalle** [comment]
Hello! Unfortunately fireorm only supports typescript. Plain javascript support is on the horizon but I'm really lacking time now.

**Comment by dogen-z** [comment]
Hello! Any update on this? Is there a timeline for this? Thanks!

**Comment by AxeemHaider** [comment]
Here is a library you can use it in NodeJs [FireO](https://github.com/octabytes/fireo-nodejs)
