### ISSUE TITLE
Consider adding to firebaseopensource.com

### ISSUE THREAD

**Issue by rosariopfernandes** [wovalle/fireorm#154]
This is a great project and it surely would be helpful for Firebase Developers. Consider [adding](https://github.com/firebase/firebaseopensource.com/issues/new?template=new_project.md) it to [firebaseopensource.com](https://firebaseopensource.com) :)

**Comment by wovalle** [comment]
Thanks!

Just [submitted](https://github.com/firebase/firebaseopensource.com/issues/175) fireorm.
