### ISSUE TITLE
How to use for calls from Firebase Client SDK?

### ISSUE THREAD

**Issue by kiptoomm** [wovalle/fireorm#163]
Hi @wovalle , this looks like a very interesting library. I was wondering how one can use it to validate the fields of a model _before_ a write event when requests are coming from the Firebase client SDKs? I can imagine how to do so when requests are coming in from a REST API call (let's say, if we expose an endpoint using Express or using HTTP cloud functions) like so:

    ...
    const userRepository = getRepository(User);
    exports.createUser = functions.https.onRequest(async (request, response) => {
        const user = await userRepository.create({
        firstName: request.query.firstName,
        lastName: request.query.LastName,
        email: request.query.emailAddress,
        password: request.query.password,
        birthDate: request.query.dateOfBirth,
        }) // => create instance of User model
    
        response.json(user.toJSON()) // return response to caller 
    }
    ...

However, I don't know how to take advantage of this library yet because my client apps use the Firebase SDK, which write directly to the document (in other words, how to 'intercept' those requests and validate them through fireorm). Would greatly appreciate any examples. I would love to use this library to 'enforce' my schema (data validation), instead of using firestore security rules

**Comment by wovalle** [comment]
I think we already had a similar discussion in https://github.com/wovalle/fireorm/issues/96. I'll close this ticket to continue it there.
