### ISSUE TITLE
Optional fields in models 

### ISSUE THREAD

**Issue by theochampion** [wovalle/fireorm#169]
Hi there,

I'm creating my firsts models and I noticed that Typescript was giving me errors when declaring the fields:

```bash
Property 'x' has no initializer and is not definitely assigned in the constructor.
```

I, therefore, had to add the definite assignment property `!` after every field (or add `| undefined` to each field type).

```dart
import { Collection } from 'fireorm';

// types
import { MediaObj } from '../types/media';

export const USERS_PUBLIC_COLLECTION = 'users_public';

@Collection(USERS_PUBLIC_COLLECTION)
export default class UserPublicModel {
  id!: string;
  display_name!: string;
  username!: string;
  pp!: MediaObj;
}
```

I could make everything assigned explicitly through the constructor, but in my case, some fields are optional. A user might not specify a display name and therefore not have a `display_name` field in his document.

What is the best way to handle that ?

Cheers! :sparkles:

**Comment by skalashnyk** [comment]
Your question is not about `fireorm`, it's about `typescript`.
By the way, you can mark such properties as optional using question mark after their names, e.g.:
`class User {
  optionalProperty?: string; // string | undefined
}`

Read more here: https://www.typescriptlang.org/docs/handbook/interfaces.html#optional-properties

**Comment by wovalle** [comment]
I think this problem solved, will close this issue.
