### ISSUE TITLE
Can it use where-in clause

### ISSUE THREAD

**Issue by RonaldCY** [wovalle/fireorm#171]
as title, like firestore library
e.g. firestore
        .collection({collection})
        .where(FieldPath.documentId(), "in", {ids});

i can select multiple doc id at once, can it do that?

thanks and regards,
Ronald

**Comment by wovalle** [comment]
Hey Ronald! Currently fireorm does not support the `in` operator and hopefully is coming soon!

**Comment by wovalle** [comment]
Update: Just realized this was being done in #123, I'll try to dedicate some time this weekend.

**Comment by RonaldCY** [comment]
Thank you very much!

**Comment by rushike** [comment]
This is not regrading the above issue, but I clearly see lack of documentation. That lead to search through whole issues, even then not get the answers for question.

I really suggest to improve the documentation, even in website, it is not enough. Example there is no clear doc to put reference field in firestore through fireorm, Means how to shape the Entity through `@Collection`  for the ref field. and many more.

The people using firestore like to have it behave as SQL, so they come in search of ORM, and if ORM is not documented it is very difficult to use for project if have very limited resources.

**Comment by wovalle** [comment]
Thanks for your comment @rushike! I'll try to add some documentation regarding the use of references.

Fireorm is a project that I work on in my spare time, I mostly focus trying to implement the most requested features but the time I can dedicate to this project is limited! Given the open source nature of fireorm, feel free to add some documentation where is lacking. Thanks!

**Comment by maheshwara-bwd** [comment]
Hey @wovalle **Great job on Fireorm man**
But as rushike said documentation is missing for many things.

It will be very helpful if you could give a quick overview on usage of references using fireorm in comment.

Please update the documentation on all your features whenever possible.

Thanks again for the effort.

**Comment by wovalle** [comment]
You can find some examples [here](https://github.com/wovalle/fireorm/blob/master/test/functional/6-document-references.int-spec.ts#L31-L62),  [here](https://github.com/wovalle/fireorm/blob/master/src/BaseFirestoreRepository.spec.ts#L452-L466) and [here](https://github.com/wovalle/fireorm/blob/master/src/BaseFirestoreRepository.spec.ts#L401-L413)

If you want to use a reference field in your Fireorm models, you'll have to create the field [as specified here](https://github.com/wovalle/fireorm/blob/master/test/functional/6-document-references.int-spec.ts#L10-L11) 

Hope it helps!

**Comment by maheshwara-bwd** [comment]
Yeah,But i still don't get how to use it via Fireorm,
Im using it via the firestore collection methods
Thanks for quick help

**Comment by wovalle** [comment]
WhereIn and whereArrayContainsAny are now available in fireorm! Closed in #178
