### ISSUE TITLE
Support pagination and realtime listening in future?

### ISSUE THREAD

**Issue by tomneo2004** [wovalle/fireorm#182]
I just started using **fireorm** and have to say it is a great library and I am wondering if pagination and realtime listening are supported in future? As roadmap seems not listed these features.

At moment, I use [custom repositories](https://fireorm.js.org/#/Custom_Repositories)with copy and modify original code to do [startAfter](https://firebase.google.com/docs/reference/js/firebase.firestore.Query#startafter).

**Comment by wovalle** [comment]
Hey!, yes, realtime listening and pagination are features that are in our roadmap! https://github.com/wovalle/fireorm/issues/1

Don't have the time or resources to set a date but is in my things to do.
