### ISSUE TITLE
Batch write is not working for subcollection

### ISSUE THREAD

**Issue by skalashnyk** [wovalle/fireorm#183]
Hi,

I've just started using subcollections and a little bit confused about using `batch write` in subcollections.
First of all, I read this thread (https://github.com/wovalle/fireorm/issues/139) and updated `fireorm` to latest version (`0.17.0`).
I also read this article - https://medium.com/@wovalle/introducing-fireorm-ba7734644684
Example of using collection described there:
```
class Album {
  id: string;
  name: string;
  year: number;
}

@Collection()
export class Band {
  id: string;
  name: string;
  formationYear: number;
  genres: Array<string>;
  @SubCollection(Album)
  albums?: ISubCollection<Album>;
}
```

Please, note, that current `ISubCollection` interface (that is alias of `IRepository<T>`) does not expose `createBatch()` method - https://github.com/wovalle/fireorm/blob/f66fe7e8c85a093d335f72a67044a73b6fa385ab/src/types.ts#L80
So, how to use batch write to subcollection?

I tried the next scenario:
```
import { ISubCollection, SubCollection, Collection, getRepository } from 'fireorm';

class Child {
  id: string;
  name: string;
}

@Collection()
class Parent {
  id: string;
  name: string;
  @SubCollection(Child)
  children?: ISubCollection<Child>;
}

(async _ => {
  try {
    const repo = getRepository(Parent);

    const created = await repo.create({
      name: 'Father'
    });

    const batch = created.children?.createBatch();

    [
      {name: 'First'},
      {name: 'Last'},
    ].forEach(child => {
      batch.create(child);
    });

    await batch.commit();

    console.log(await created.children.find()); // empty array
  } catch (e) {
    console.error(e);
  }
})();
```
This code snippet creates new `"children"` collection (in root of firestore)

**Expected behaviour**
1 document in `"Parents"` collection and 2 documents in `"children"` subcollection (of this "perent" doc) were created.

**Actual behaviour**
1 document in `"Parents"` collection and 2 documents in `"children"` collection (as root collection) were created.

I'm observing this in (at least) `0.17.0` and `0.14.0` (that is referenced in this thread (#139) as one that resolves the issue).
`0.12.1` (that I have installed) works as expected

P.S. Creation of single document in subcollection works as expected

**Comment by skalashnyk** [comment]
It seems it might be fixed by adding `collectionPath` to 
1) this method signature: https://github.com/wovalle/fireorm/blob/f66fe7e8c85a093d335f72a67044a73b6fa385ab/src/Batch/FirestoreBatch.ts#L38
2) this constructor invocation: https://github.com/wovalle/fireorm/blob/f66fe7e8c85a093d335f72a67044a73b6fa385ab/src/Batch/FirestoreBatch.ts#L39
3) this method invocation: https://github.com/wovalle/fireorm/blob/master/src/BaseFirestoreRepository.ts#L95

**Comment by wovalle** [comment]
Issues like this is the reason why I started #172 and refactor fireorm to use paths natively instead of a hack. I haven't had time to finish this task but I will soon.

**Comment by skalashnyk** [comment]
@wovalle, thanks for reply.
May I suggest pull-request to fix this or just waiting for your fix?
Can I help some way? I.e. write tests etc.? 
Current code does not pass tests for batch write I wrote...

**Comment by wovalle** [comment]
You can make a PR to add a workaround for the batches in the meantime and I'll merge it to master. If you add some tests I'll make sure they pass before merging my branch.

 I'll get back to my PR ASAP.

**Comment by skalashnyk** [comment]
@wovalle, my colleague Yaroslav @Fame513 prepared fix for this - https://github.com/wovalle/fireorm/pull/186.
Please, review and approve.
Thanks!
