### ISSUE TITLE
Everything that I send is being created

### ISSUE THREAD

**Issue by talesmgodois** [wovalle/fireorm#190]
Before anything, I'm going to say that I loved the project guys. I was wondering about something like this for some days.

So, I found something kind of **weird**, at least for me.

I have created the following collection. When I trigger  it's creating other fields that does not belongs to my defined collection. In other words, for the following collection, it's creating other fields if I send, not just **id** and **name**.  Is there a way to avoid this? I would like to not add extra fields even if I send it.

```
import "../firebase";
import { Collection, getRepository } from 'fireorm';

@Collection()
export class Project {
  id: string;
  name: string;
}

export const ProjectRepository = getRepository(Project);
```

**Comment by wovalle** [comment]
Hello! Collections in firestore should only have the fields that are defined in your class. At minimum, a collection should have an `id` field, but that's the only requirement.

Which other fields are being created?

**Comment by talesmgodois** [comment]
Well, Any data that I send as body of my post request is being stored. 
For example. If I send the following JSON to the follwing collection. The **lastName** is being stored plus **name** and **id**( theses last two were supposed to store because of the collection definition)

```
{
     "name": "Tales",
     "lastName": "Godois"
}

@Collection()
 export class Project {
  id: string;
  name: string;
}


```

**Comment by wovalle** [comment]
Hey! Sorry for the late response. 

I still don't fully understand what do you mean by "body of your post request". Did you declare a fireorm model and then tried to add some documents through firestore api?

**Comment by wovalle** [comment]
Closed due to inactivity. Will reopen if problem persists!
