### ISSUE TITLE
[Question] Is it possible to use fireorm inside a frontend project?

### ISSUE THREAD

**Issue by leandrowkz** [wovalle/fireorm#193]
Hi guys! First, thanks for building this package.

I've read the Usage section in the official documentation at https://fireorm.js.org, which says to initialize the firestore application by using the package ```firebase-admin```.

However, this package is mostly intended to be used on node.js backend applications, so my questions are:

1) Fireorm is designed to be used only on scenarios where ```firebase-admin``` is possible?
2) Is there a way to use fireorm inside a frontend app without depending on ```firebase-admin```?

**Comment by wovalle** [comment]
Hey! Client support is something I'm looking for [is even in my roadmap[(https://github.com/wovalle/fireorm/issues/1) but haven't had time to plan it correctly. It'll require a heavy refactor of the core logic to abstract some stuff but it is possible.

So basically I want to do it but haven't dedicated time to it.

**Comment by leandrowkz** [comment]
Thanks for the answer, @wovalle!
