### ISSUE TITLE
[FEATURE] Not equal queries

### ISSUE THREAD

**Issue by pereslavtsev** [wovalle/fireorm#205]
Firestore now supports not equal queries - https://firebase.googleblog.com/2020/09/cloud-firestore-not-equal-queries.html

- https://firebase.google.com/docs/firestore/query-data/queries#not_equal
- https://firebase.google.com/docs/firestore/query-data/queries#in_and_array-contains-any

Can we implement new methods like a `whereNotEqualTo`and `whereNotIn` ?

**Comment by wovalle** [comment]
Thanks for the suggestion! Not so many changes has to be done. If someone wants to pick this up before me go ahead!

**Comment by fpolica91** [comment]
> Thanks for the suggestion! Not so many changes has to be done. If someone wants to pick this up before me go ahead!

Adding the properties to FirestoreOperators and creating functions on QueryBuilder, more or less, right?

**Comment by wovalle** [comment]
Along with some unit tests.

You can use https://github.com/wovalle/fireorm/pull/178/files as guidance.

**Comment by wovalle** [comment]
closed in #224
