### ISSUE TITLE
[FEATURE] Add constructor possibility to Collection decorator

### ISSUE THREAD

**Issue by jpc0rrea** [wovalle/fireorm#206]
If I try to create a model today with fireorm, I can't use a constructor.

![Captura de tela de 2020-11-11 22-18-28](https://user-images.githubusercontent.com/56732309/98883017-58cf9880-246c-11eb-96f3-5cca17f2ab7d.png)

So, I have to use the model in this way:

`

    class CreateVariableService {
      public async execute({ name, value }: Request): Promise<Variable> {
        const variableRepository = getRepository(Variable);

        const variablesWithSameName = await variableRepository
          .whereEqualTo('name', name)
          .find();

        if (variablesWithSameName.length > 0) {
          throw new AppError(`System variable ${name} already exists.`, 401);
        }

        const hashedValue = await hash(value, 8);

        const variable = new Variable();

        variable.name = name;
        variable.value = hashedValue;
        variable.createdAt = new Date().toISOString();
        variable.updatedAt = new Date().toISOString();

        await variableRepository.create(variable);

        return variable;
      }
    }
`

Whats I want is to be possible to create a new instance of a model like:

`

    class CreateVariableService {
      public async execute({ name, value }: Request): Promise<Variable> {
        const variableRepository = getRepository(Variable);

        const variablesWithSameName = await variableRepository
          .whereEqualTo('name', name)
          .find();

        if (variablesWithSameName.length > 0) {
          throw new AppError(`System variable ${name} already exists.`, 401);
        }

        const hashedValue = await hash(value, 8);

        const variable = new Variable({name, value: hashedValue});

        await variableRepository.create(variable);

        return variable;
      }
    }

`

**Comment by AlexanderArvidsson** [comment]
You can implement this yourself:
```
import { Collection, getRepository, IEntity } from 'fireorm';

type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;

class Entity<T extends IEntity> {
  constructor(params?: Optional<T, 'id'>) {
    if (params) {
      Object.assign(this, params);
    }
  }
}

@Collection('test')
export class Test extends Entity<Test> {
  id: string;
  name: string;
}

const test = new Test({ name: "Hello" })
getRepository(Test).create(test);
```

You can now pass fields, and the `id` field will also be optional if you'd ever need that. If you don't need `id` to be optional, you can switch `Optional<T, 'id'>` with `Omit<T, 'id'>`

**Comment by wovalle** [comment]
@jpc0rrea fireorm by default requires a no-args constructor, but typescript supports constructor overloads and you can do kind of a factory implementation as sugested by @AlexanderArvidsson.

closing in favor of #117
