### ISSUE TITLE
Transactions limit, orderByAscending, orderByDescending

### ISSUE THREAD

**Issue by LukaszKuciel** [wovalle/fireorm#208]
Hi guys,
I need to use transactions along with orderByAscending to process messages queue in proper order. 
I found this code in fireorm:
```ts
limit(): IQueryBuilder<T> {
    throw new Error('`limit` is not available for transactions');
  }

  orderByAscending(): IQueryBuilder<T> {
    throw new Error('`orderByAscending` is not available for transactions');
  }

  orderByDescending(): IQueryBuilder<T> {
    throw new Error('`orderByDescending` is not available for transactions');
  }
```
Is there any specific reason for that or this is on the list of features waiting to implement?

**Comment by wovalle** [comment]
Ordering and limit are not available in Firestore transaction objects as
far as I know, that's why is not implemented.

**Comment by wovalle** [comment]
Closed due to inactivity. If this is supported by firestore I'll happily reopen.
