### ISSUE TITLE
Please explain more about Document Reference field in the documentation 

### ISSUE THREAD

**Issue by anhzf** [wovalle/fireorm#221]
I've read this issue #32 too, but it's not solved for me. I'm working with vue it says `Maximum call stack size exceeded`

**Comment by wovalle** [comment]
#32 refers to a feature (relationships) that was being planned but not implemented in the codebase. You can find more info about Document References in the [documentation](https://fireorm.js.org/#/Read_Data?id=search-by-document-reference)

**Comment by kay-es** [comment]
+1

I also get ```Maximum call stack size exceeded``` when using references (according to the documentation). Did anything change in the api?

**Comment by wovalle** [comment]
Can you reproduce `Maximum call stack size exceeded` in a tiny example that I can check? @kay-es
