### ISSUE TITLE
Incorrect type for `BaseFirestoreRepository#create`

### ISSUE THREAD

**Issue by johanneslumpe** [wovalle/fireorm#226]
According to the source, `BaseFirestoreRepository#create` should take `PartialBy<T, 'id'>`, but the generated declaration actually type create as `create(item: T): Promise<T>;`. The type is correct on `TransactionRepository`. I wonder if something odd is going on during declaration generation?

**Comment by wovalle** [comment]
Are you using the last version?

This is the type that is being exported: 
![image](https://user-images.githubusercontent.com/7854116/104828962-1dbf5c00-5845-11eb-8ba1-5cacc349bcb2.png)

**Comment by johanneslumpe** [comment]
Oh no, I was on 0.17.2. I just recently installed that version, didn’t realize there had been two releases after it so quickly. My bad!

**Comment by wovalle** [comment]
Glad that is solved! 😄
