### ISSUE TITLE
Usage with Admin Bro

### ISSUE THREAD

**Issue by aleccool213** [wovalle/fireorm#227]
Just wondering if anyone had any success?

I see [an adapter exists for Firestore already](https://www.npmjs.com/package/@tirrilee/admin-bro-firebase) but I would like to use this ORM if possible.

**Comment by wovalle** [comment]
Thanks for the interest in fireorm! I had no idea of AdminBro but it seems that a different adapter must be created to support fireorm.

Closing as this is not a problem of fireorm itself
