### ISSUE TITLE
Customized repository of any type

### ISSUE THREAD

**Issue by shidcordero** [wovalle/fireorm#231]
I want to customized all my repository to add a custom method of `.where()`

This is suppose to what I imagine

	import { BaseFirestoreRepository, CustomRepository, getRepository } from 'fireorm';

	@CustomRepository(T)
	class CustomBandRepository extends BaseFirestoreRepository<T> {
	  async where(): BaseFirestoreRepository<T> {
            // logic here
	    return this
	  }
	}

**Comment by wovalle** [comment]
Hey! Somehow I missed this issue.

This is accomplished by using [Custom Repositories](https://fireorm.js.org/#/Custom_Repositories).
