### ISSUE TITLE
Add settings to the Initialize docs

### ISSUE THREAD

**Issue by arnaldoperez** [wovalle/fireorm#242]
Hello!

I'm starting using this ORM and I found myself in the need to add this settings to my Firestore initialization. I think this should be in the docs in the "Initialize" section of https://fireorm.js.org/#/README, and in all the other places that shows how to get started with this ORM.

This is needed when you set an object property as optional, and if you don't set it up like this, you'll get an error on Firebase writing. It works fine in the emulator, but in production I won't work

```javascript
const app = initializeApp()

const db= app.firestore()
db.settings({
  ignoreUndefinedProperties: true
})

fireorm.initialize(db)
```

**Comment by wovalle** [comment]
The initialization settings you use when initializing firestore shouldn't be documented in fireorm unless it changes its behavior.
