### ISSUE TITLE
Timestamps returned by `BaseFireStoreRepository` methods such as `findById` do not match the Collection type

### ISSUE THREAD

**Issue by braaar** [wovalle/fireorm#277]
I have faced some issues when using `Timestamp` fields such as in this example Collection class:

```ts
import { Collection } from 'fireorm';
import { Timestamp } from '@google-cloud/firestore';

@Collection('persons')
export class Person {
  name: string;

  id: string;

  createdAt: Timestamp;
}
```

Here's an example of how I store and retrieve the data from firestore (I made a simplified example):
```ts
import { Timestamp } from '@google-cloud/firestore';
import { BaseFirestoreRepository } from 'fireorm';
import { Person } from '../models/person.model';

export class PersonService {
  constructor(
    private readonly personRepository: BaseFirestoreRepository<Person>,
  ) {}
  async getPerson(id: string): Promise<Person> {
    return this.personRepository.findById(id);
  }
  async createPerson(name: string): Promise<Person> {
    const personToCreate: Omit<Person, 'id'> = {
      name,
      createdAt: Timestamp.now(),
    };
    return await this.personRepository.create(personToCreate);
  }
}
```

The `Person` that is returned by `findById` claims to be a `Person` according to the Collection class specification. But after some fiddling around with errors, I discovered that the timestamp we get from `findById` is not a `@google-cloud/firestore` timestamp like the type `Person` would indicate. 

Here is what we would expect:
```ts
{
  seconds: number;
  nanoseconds: number;
}
```

And here is what I actually get:

```ts
{
  _seconds: number;
  _nanoseconds: number;
}
```

Has anyone else faced this issue?
While this might ultimately stem from an issue or quirk in Firestore, I think Fireorm would be better off if it was able to type the incoming data from Firestore correctly. I like being able to trust the types I am presented with.

If I'm missing something or should provide more information in this issue, please let me know!

**Comment by braaar** [comment]
> Hi @braaar.
> 
> Have you tried typing `createdAt` as Date? It'll be automatically be converted to a timestamp in firestor. If Date is not an option, can you make a tiny repo that I can clone and reproduce this issue?
> 
> This seems to be a problem handling firestore complex types (timestamp) but I haven't used Timestamp in my models before

Hi, and thanks for the reply! I can try that. Is it firestore or fireorm that does the conversion from Dates? Are timestamps automatically converted back to Dates when fetching data with `findById`? 

I'll try to set up a small repo to reproduce the issue.

**Comment by braaar** [comment]
I switched to using `Date` instead of `Timestamp` in my project, which has been working perfectly. 

I haven't gotten around to setting up a small repo for this yet since I don't really need the fix anymore, so I guess this issue can be closed and, at a later point, potentially reopened if someone else faces the same issue.

**Comment by wovalle** [comment]
Thanks for reporting! closing now.
