### ISSUE TITLE
Can't resolve 'class-validator' typescript

### ISSUE THREAD

**Issue by andirsun** [wovalle/fireorm#278]
After install and initialize as in the web the typescript compilator show me the error
```Can't resolve 'class-validator' ```
![Screenshot from 2021-10-06 19-04-04](https://user-images.githubusercontent.com/22928302/136300051-59289fe3-9653-458c-8873-6f200f24c8bc.png)
I solved installing ```class-validator``` and ```@types/class-validator```

**Comment by wovalle** [comment]
What version of fireorm are you using?

This should be fixed in the last one (v0.23.0)
