### ISSUE TITLE
Getter methods decorated with @Ignore() are still saved

### ISSUE THREAD

**Issue by DanielRHarris** [wovalle/fireorm#282]
Hi,

It seems that Getter methods decorated with @Ignore() are still saved when they're converted to properties.

For example, the following will store the property CapitalizedName, despite the @Ignore() decorator.

```typescript
@Collection()
class Band {
  id: string;
  name: string;

  @Ignore()
  public get CapitalizedName(): string { this.name.charAt(0).toUpperCase() + this.name.slice(1) }
}
```

**Comment by danieleisenhardt** [comment]
Hi,

I didn't think of this at all when creating the @Ignore() decorator. I will see if I can find a solution and create a PR for it once I have the time, unless you beat me to it of course.

**Comment by wovalle** [comment]
Hey! Sorry I missed this issue. Sadly right now I don't have time to fix it but it should be an easy fix
