### ISSUE TITLE
Querying missing fields

### ISSUE THREAD

**Issue by RaphBlanchet** [wovalle/fireorm#314]
Hey,

First of all, thanks for the package, it's really useful to have an ORM like this for Firestorm, and works great too!

I was wondering if it's possible to use a `whereEqualTo` on a missing field in a document?

The use case I have is this : 

- Multiple documents of the same model were created with, let's say, fields X and Y
- I want to add a new field, Z, which its default value is `null`
- I don't want to run a migration on all existing documents just to add `Z: null`
- Is it then possible to query my documents to find which one are either missing `Z` (old documents) or having `null` (newly created documents)?

I tried it and I don't get the results I want!

Can I accomplish that with a custom query?

Thanks!

**Comment by wovalle** [comment]
Hey Raph!

I'm wondering how you'd query documents without an specific key in plain firestore, that query should be portable to fireorm and if not you can build your own [custom query](https://github.com/wovalle/fireorm/issues/244#issuecomment-811512104)

**Comment by RaphBlanchet** [comment]
Yeah I read afterward that this is a limitation of Firestore, unfortunately! I'm new to NoSQL, I guess I'm too used to relational databases and need to change my mindset! 😅 Thanks!

**Comment by wovalle** [comment]
You're welcome!
