### ISSUE TITLE
Error: Firestore must be initialized first - on using customRepository

### ISSUE THREAD

**Issue by nagapriyanka** [wovalle/fireorm#323]
Using nestjs-fireorm, I am facing this below issue while creating a customRepository which extends on BaseFirestoreRepository

**Error: Firestore must be initialized first**
    at userCustomRepository.AbstractFirestoreRepository [as constructor] firestore_fireorm\node_modules**\fireorm\lib\src\AbstractFirestoreRepository.js:159:19)**

`import { BaseFirestoreRepository, CustomRepository } from 'fireorm';
import { User } from '../entities/user.entity';

@CustomRepository(User)
export class userCustomRepository extends BaseFirestoreRepository<User>{`
It's not working as expected, Referred official Document : [https://fireorm.js.org/#/Custom_Repositories](url)

Files Attached for reference below.

![customRepo_gitIssue](https://user-images.githubusercontent.com/22192381/224635802-a5d4b8ef-0a82-451c-af71-949b2284d456.PNG)
![FireormcustomRepo_err](https://user-images.githubusercontent.com/22192381/224635814-f8f1a513-78d3-4c52-8726-74104c8a616e.PNG)

@wovalle 
Need your help.

**Comment by priyanka-nc** [comment]
@wovalle Can you please have a look into this

**Comment by wovalle** [comment]
Hey @nagapriyanka @priyanka-nc!

This doesn't seem to be a fireorm problem. But a problem with how nestjs is loading the dependencies. Before calling `CustomRepository` you need to have initialize firestore (hence the error). In a plain node app this is trivial, you call `fireorm.initialize(firestore)` in your setup/initial file before you load any file that might use custom repositories but I have no experience working with nest-js or how things are done in that framework.

I'd advise going to the `nestjs-fireorm` project and asking advice there.
