### ISSUE TITLE
Example for Transaction

### ISSUE THREAD

**Issue by jeemyeong** [wovalle/fireorm#74]
I knew several orms support transactions (ex. [typeorm](https://github.com/typeorm/typeorm/blob/master/docs/transactions.md)).
Do you have any idea with transactions?

**Comment by wovalle** [comment]
Sorry but Fireorm doesn't support Transactions at the moment. It's listed in the [roadmap](https://github.com/wovalle/fireorm/issues/1). Hopefully I'll have time in the next weeks to sit down and implement it.

**Comment by wovalle** [comment]
Hey! Recently I added transactions support!

I'll be working in the documentation soon but [here is an example](https://github.com/wovalle/fireorm/blob/master/test/functional/4-transactions.spec.ts) in how to use them.

**Comment by jeemyeong** [comment]
@wovalle Thanks!
