### ISSUE TITLE
Support for Document References in where methods

### ISSUE THREAD

**Issue by popcorn245** [wovalle/fireorm#82]
In firestore you can pass a document reference to a where method as the value in order to query by references tied to documents. If we had a collection of todos and each document had a user reference tied to it who owned the todo, I might write something like this.

```
todoCollection.where("user", "==", userRef).get();
```

Per our discussion of Twitter, it seems that this should be as simple as updating the typings and writing some tests.

**Comment by wovalle** [comment]
Hey! I [started working with this issue](https://github.com/wovalle/fireorm/tree/feature/document-references-in-where-methods) found a road block (probably related to #58). Before continuing, I'd like you to expand your use case.

Are you using `firestore.collection` along with fireorm models? How do you represent that reference in your models?

**Comment by wovalle** [comment]
This was closed in #105. See [this example](https://github.com/wovalle/fireorm/blob/master/src/BaseFirestoreRepository.spec.ts#L455-L469)

**Comment by popcorn245** [comment]
Thanks @wovalle you are the man! ^_^
