### ISSUE TITLE
Don't understand update or missing methods?

### ISSUE THREAD

**Issue by maximelebreton** [wovalle/fireorm#94]
Hello,

On an existing document:
```js
{
  id: 'rush'
  a: 'a',
  b: 'b'
}
```
if made this:
```js
const bandRepository = GetRepository(Band);
const rush = await bandRepository.findById('rush');
delete rush.a // remove the a entry
await bandRepository.update(rush);
```
the document should be:
```js
{
  id: 'rush'
  b: 'b'
}
```

But actually it keeps the `a` entry...

On Firestore we have the `merge` option to define if we want to **merge** or **replace**:
```js
set(
  rush,
  {merge: true}
)
```

What is the equivalent for `fireorm` ? I can't find it on the documentation.

Thanks!

**Comment by wovalle** [comment]
Given that classes are the blueprint of firestore documents, deleting a class property was never the intended way to clear its content. Setting the property to null is.

Any particular reason why you want to delete the property?

**Comment by manwithsteelnerves** [comment]
@wovalle  I see your point.
Can you please confirm currently it replaces or merges?

**Comment by wovalle** [comment]
It currently replaces. There has been some conversation about adding a merge feature but we've had no end so far. 

To delete a property from an object I would set it to `null`.
